// footfall Worker — footfall.bisks.net
//
// @angussoftware.dev asked for a leaderboard of every site the bot has made,
// ranked by visits / time-on-page, plus leaderboards for the prompters whose
// sites draw the most traffic. This is the real (not fabricated) tracker:
// public/beacon.js is a tiny script other sites embed. It reports a "hit" on
// load and a "dwell" duration (ms on page) on pagehide/tab-hide to the
// FootBoard Durable Object below, which keeps cumulative per-site totals.
//
// The leaderboard page (public/index.html) fetches /api/leaderboard for the
// live counts and public/data/manifests.json — a static snapshot of every
// sites/*/site.json, regenerated by sync-manifests.mjs (same pattern as
// sites/receipts' sync-asks.mjs) — for the site→prompter join, and rolls
// per-prompter totals up client-side.

export interface DurableObjectId {
  toString(): string;
}
export interface DurableObjectStub {
  fetch(request: Request): Promise<Response>;
}
export interface DurableObjectNamespace {
  idFromName(name: string): DurableObjectId;
  get(id: DurableObjectId): DurableObjectStub;
}
export interface DurableObjectStorage {
  get<T = unknown>(key: string): Promise<T | undefined>;
  put(entries: Record<string, unknown>): Promise<void>;
}
export interface DurableObjectState {
  storage: DurableObjectStorage;
  blockConcurrencyWhile<T>(fn: () => Promise<T>): Promise<T>;
}

export interface Env {
  ASSETS: { fetch: (req: Request) => Promise<Response> };
  BOARD: DurableObjectNamespace;
}

const CORS_HEADERS = {
  "access-control-allow-origin": "*",
  "access-control-allow-methods": "GET, POST, OPTIONS",
  "access-control-allow-headers": "content-type",
};

// ---- very light per-IP throttle on the API, ahead of the DO ----------------
// Best-effort only (resets on cold start / redeploy, not shared across
// isolates) — same shape as sites/tallybot. The real ceiling against abuse is
// the DO's MAX_SITES cap and the per-request payload validation below.
const RATE_WINDOW_MS = 60_000;
const RATE_MAX = 240;
const rateBuckets = new Map<string, { count: number; resetAt: number }>();
function rateLimited(ip: string): boolean {
  const now = Date.now();
  const b = rateBuckets.get(ip);
  if (!b || now > b.resetAt) {
    rateBuckets.set(ip, { count: 1, resetAt: now + RATE_WINDOW_MS });
    return false;
  }
  b.count++;
  return b.count > RATE_MAX;
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);

    if (url.pathname.startsWith("/api/")) {
      if (request.method === "OPTIONS") {
        return new Response(null, { status: 204, headers: CORS_HEADERS });
      }
      const ip = request.headers.get("cf-connecting-ip") || "unknown";
      if (rateLimited(ip)) {
        return new Response(JSON.stringify({ error: "slow down" }), {
          status: 429,
          headers: { "content-type": "application/json", ...CORS_HEADERS },
        });
      }
      const stub = env.BOARD.get(env.BOARD.idFromName("global"));
      const res = await stub.fetch(request);
      const headers = new Headers(res.headers);
      for (const [k, v] of Object.entries(CORS_HEADERS)) headers.set(k, v);
      return new Response(res.body, { status: res.status, headers });
    }

    return env.ASSETS.fetch(request);
  },
};

// ---------------------------------------------------------------------------
// FootBoard — the one global Durable Object. Holds cumulative visit/dwell
// totals per site name, written by the beacon on every other site.
// ---------------------------------------------------------------------------

interface SiteStats {
  site: string;
  visits: number;
  dwellMs: number;
  dwellSamples: number;
  firstSeenAt: number;
  lastSeenAt: number;
}

const MAX_SITES = 5_000; // storage ceiling — comfortably above the ~420 real sites
const MAX_SITE_LEN = 64;
const MAX_DWELL_MS = 30 * 60 * 1000; // clamp a single reported dwell to 30 minutes

function json(data: unknown, status = 200): Response {
  return new Response(JSON.stringify(data), {
    status,
    headers: { "content-type": "application/json" },
  });
}

// Site names are directory names: lowercase letters, digits, hyphens only.
// Anything else (or too long) is rejected rather than coerced, so garbage
// input never silently lands under a mangled key.
function normalizeSite(raw: unknown): string | null {
  if (typeof raw !== "string") return null;
  const s = raw.trim().toLowerCase();
  if (!s || s.length > MAX_SITE_LEN) return null;
  if (!/^[a-z0-9][a-z0-9-]*$/.test(s)) return null;
  return s;
}

export class FootBoard {
  private state: DurableObjectState;
  private ready: Promise<void>;
  private sites: Map<string, SiteStats> = new Map();

  constructor(state: DurableObjectState) {
    this.state = state;
    this.ready = this.state.blockConcurrencyWhile(async () => {
      const stored = await this.state.storage.get<Record<string, SiteStats>>("sites");
      if (stored) this.sites = new Map(Object.entries(stored));
    });
  }

  private async persist(): Promise<void> {
    await this.state.storage.put({ sites: Object.fromEntries(this.sites) });
  }

  private ensure(site: string, now: number): SiteStats | null {
    let s = this.sites.get(site);
    if (!s) {
      if (this.sites.size >= MAX_SITES) return null;
      s = { site, visits: 0, dwellMs: 0, dwellSamples: 0, firstSeenAt: now, lastSeenAt: now };
      this.sites.set(site, s);
    }
    return s;
  }

  async fetch(request: Request): Promise<Response> {
    await this.ready;
    const url = new URL(request.url);
    const now = Date.now();

    if (url.pathname === "/api/hit" && request.method === "POST") {
      let body: any;
      try {
        body = await request.json();
      } catch {
        return json({ error: "bad json" }, 400);
      }
      const site = normalizeSite(body?.site);
      if (!site) return json({ error: "bad site" }, 400);
      const s = this.ensure(site, now);
      if (!s) return json({ error: "at capacity" }, 507);
      s.visits += 1;
      s.lastSeenAt = now;
      await this.persist();
      return json({ ok: true });
    }

    if (url.pathname === "/api/dwell" && request.method === "POST") {
      let body: any;
      try {
        body = await request.json();
      } catch {
        return json({ error: "bad json" }, 400);
      }
      const site = normalizeSite(body?.site);
      const ms = typeof body?.ms === "number" && Number.isFinite(body.ms) ? body.ms : null;
      if (!site || ms === null || ms <= 0) return json({ error: "bad payload" }, 400);
      const s = this.ensure(site, now);
      if (!s) return json({ error: "at capacity" }, 507);
      s.dwellMs += Math.min(ms, MAX_DWELL_MS);
      s.dwellSamples += 1;
      s.lastSeenAt = now;
      await this.persist();
      return json({ ok: true });
    }

    if (url.pathname === "/api/leaderboard" && request.method === "GET") {
      const rows = [...this.sites.values()].map((s) => ({
        ...s,
        avgDwellMs: s.dwellSamples > 0 ? Math.round(s.dwellMs / s.dwellSamples) : 0,
      }));
      const totals = rows.reduce(
        (acc, r) => {
          acc.visits += r.visits;
          acc.dwellMs += r.dwellMs;
          return acc;
        },
        { visits: 0, dwellMs: 0 },
      );
      return json({ sites: rows, totals, trackedSites: rows.length });
    }

    if (url.pathname === "/api/site" && request.method === "GET") {
      const site = normalizeSite(url.searchParams.get("name"));
      if (!site) return json({ error: "bad site" }, 400);
      const s = this.sites.get(site);
      if (!s) return json({ site, visits: 0, dwellMs: 0, dwellSamples: 0, avgDwellMs: 0 });
      return json({ ...s, avgDwellMs: s.dwellSamples > 0 ? Math.round(s.dwellMs / s.dwellSamples) : 0 });
    }

    return json({ error: "not found" }, 404);
  }
}
