// Served at the root of belvedere.bisks.net. The survey data is a static
// build-time artifact (public/data/survey.json, generated by
// audit/atproto-survey.mjs), so there's no server-side behavior here — just
// forward everything to the static-asset router.
export interface Env {
  ASSETS: { fetch: (req: Request) => Promise<Response> };
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    return env.ASSETS.fetch(request);
  },
};
