name = "atprotozoa-arachnid2027"
main = "src/index.ts"
compatibility_date = "2025-01-01"

routes = [
  { pattern = "arachnid2027.bisks.net/*", zone_name = "bisks.net" },
]

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = true
