// Emits public/Blueskyisms.lean from public/data/propositions.json.
// Core Lean 4 only (no Mathlib): the ontology is a finite graph, so each
// theorem is a closed computation the kernel checks with `decide`.
// Usage: node gen-lean.mjs
import { readFileSync, writeFileSync } from "node:fs";

const props = JSON.parse(readFileSync("public/data/propositions.json", "utf8"));
const idx = new Map(props.map((p, i) => [p.id, i]));
const edges = (t) => props.flatMap((p, i) => p.links.filter((l) => l.type === t).map((l) => [i, idx.get(l.to)]));
const sup = edges("supports"), ten = edges("tensions"), qua = edges("qualifies");
const pairs = (es) => "[" + es.map(([a, b]) => `(${a}, ${b})`).join(", ") + "]";

// Same closure the Lean code computes, so the stated theorems are the true ones.
const reach = (a) => {
  let s = new Set([a]), grew = true;
  while (grew) { grew = false; for (const [x, y] of sup) if (s.has(x) && !s.has(y)) { s.add(y); grew = true; } }
  return s;
};
const num = (i) => props[i].num;
const grounded = props.map((_, i) => i).filter((i) => reach(i).has(0));
const ungrounded = props.map((_, i) => i).filter((i) => !reach(i).has(0));
const circular = props.map((_, i) => i).filter((i) => [...reach(i)].some((j) => j !== i && reach(j).has(i)));
const nat = (xs) => "[" + xs.join(", ") + "]";
const names = props.map((p) => `  "${p.num}"`).join(",\n");

const out = `/-
  Blueskyisms.lean — a formalization of the Tractatus Logico-Blueskyicus.
  Generated by gen-lean.mjs from data/propositions.json. Core Lean 4, no Mathlib.

  Each proposition is its index in \`nums\`. An edge (a, b) in \`supports\` reads
  "a supports b". Every theorem below is a closed computation on a finite graph,
  so \`decide\` closes it.
-/

namespace Blueskyisms

/-- Proposition numbers, in the order of the book. -/
def nums : List String := [
${names}
]

def supports : List (Nat × Nat) := ${pairs(sup)}
def tensions : List (Nat × Nat) := ${pairs(ten)}
def qualifies : List (Nat × Nat) := ${pairs(qua)}

/-- Remove duplicates, keeping first occurrences. -/
def dedup (xs : List Nat) : List Nat :=
  xs.foldl (fun acc x => if acc.contains x then acc else acc ++ [x]) []

/-- One round of following \`supports\` edges outward from a set. -/
def step (s : List Nat) : List Nat :=
  dedup (s ++ supports.filterMap fun (e : Nat × Nat) => if s.contains e.1 then some e.2 else none)

/-- Iterate \`step\`. The graph has ${props.length} nodes, so ${props.length} rounds always reach the fixpoint. -/
def closure : Nat → List Nat → List Nat
  | 0, s => s
  | n + 1, s => closure n (step s)

/-- \`reaches a b\`: a chain of supports leads from a to b. -/
def reaches (a b : Nat) : Bool := (closure ${props.length} [a]).contains b

/-- Proposition 1, "The timeline is everything that suffers", is the root. -/
def root : Nat := 0

/-- A proposition is grounded when a chain of supports leads to the root. -/
def grounded (a : Nat) : Bool := reaches a root

/-- The root has no outgoing support: nothing holds it up. -/
theorem root_unsupported : supports.filter (fun e => e.1 == root) = [] := by decide

/-- Exactly these propositions are grounded in 1. -/
theorem grounded_set :
    (List.range ${props.length}).filter grounded = ${nat(grounded)} := by decide

/-- Exactly these propositions are never grounded: their support runs into a dead end. -/
theorem ungrounded_set :
    (List.range ${props.length}).filter (fun a => !grounded a) = ${nat(ungrounded)} := by decide

/-- ${num(idx.get("6"))} (${props[idx.get("6")].text.split(":")[0]}) is not grounded: the chain from it never touches the root. -/
theorem discourse_ungrounded : grounded ${idx.get("6")} = false := by decide

/-- Mutual support, no way out: ${circular.map(num).join(", ")} support each other in a loop. -/
theorem circular_set :
    (List.range ${props.length}).filter (fun a =>
      (List.range ${props.length}).any fun b => a != b && reaches a b && reaches b a) = ${nat(circular)} := by decide

${circular.length >= 2 ? `/-- The Circular Citation, formally: ${num(circular[0])} and ${num(circular[1])} each support the other. -/
theorem circular_citation : reaches ${circular[0]} ${circular[1]} = true ∧ reaches ${circular[1]} ${circular[0]} = true := by decide
` : ""}
/-- The ontology is not a tree: ${props.length} propositions, ${sup.length} supports, ${ten.length} tensions, ${qua.length} qualifications. -/
theorem sizes : nums.length = ${props.length} ∧ supports.length = ${sup.length} ∧ tensions.length = ${ten.length} ∧ qualifies.length = ${qua.length} := by decide

end Blueskyisms
`;
writeFileSync("public/Blueskyisms.lean", out);
console.log({ grounded: grounded.map(num), ungrounded: ungrounded.map(num), circular: circular.map(num) });
