// rateyourbuild Worker — mounted at its own subdomain, rateyourbuild.bisks.net.
//
// Everything here is static + client-side (per the frontend-first house
// rule): the catalog of rateable sites is a build-time snapshot of every
// sites/*/site.json manifest (public/data/catalog.json, regenerated by
// sync-catalog.mjs — same recipe as sites/receipts/sync-asks.mjs), and the
// ratings themselves are net.bisks.rateyourbuild.rating records written to
// each rater's own PDS and read back network-wide via
// listReposByCollection + a live Jetstream subscription
// (public/lib/global-index.js, copied from sites/steamtags — see
// notes/ideas/pds-and-lexicons.md, "Tier 3"). No server-side state at all,
// so the Worker's only job is handing back static assets.
export interface Env {
  ASSETS: { fetch: (req: Request) => Promise<Response> };
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    return env.ASSETS.fetch(request);
  },
};
