// rateyourbuild Worker — mounted at its own subdomain, rateyourbuild.bisks.net.
//
// Everything here is static + client-side (per the frontend-first house
// rule): the catalog of rateable sites is a build-time snapshot of every
// sites/*/site.json manifest (public/data/catalog.json, regenerated by
// sync-catalog.mjs — same recipe as sites/receipts/sync-asks.mjs), and the
// ratings/reviews themselves are net.bisks.rateyourbuild.rating records
// written to each rater's own PDS and read back network-wide via
// listReposByCollection + a live Jetstream subscription
// (public/lib/global-index.js, copied from sites/steamtags — see
// notes/ideas/pds-and-lexicons.md, "Tier 3").
//
// The one thing that needed a server: per-site and per-genre pages
// (/site/<name>, /genre/<key>, /super/<key>) need their own og:title /
// og:description / og:url so a shared link unfurls as that specific site or
// genre, not one generic card for every URL — same problem and same fix as
// sites/didscope's /s/<handle> (notes/45-sharing-and-virality.md, tier 4):
// the Worker fetches the static shell from ASSETS and stamps the real meta
// values in before serving it. The client script (public/index.html) reads
// location.pathname itself to render the matching detail view — this Worker
// route only has to get the *meta tags* right for crawlers/unfurlers, since
// a real browser runs the JS regardless.
import catalog from "../public/data/catalog.json";
import { GENRES, SUPERS } from "../public/lib/genres.js";

export interface Env {
  ASSETS: { fetch: (req: Request) => Promise<Response> };
}

type CatalogSite = {
  name: string;
  url: string;
  title: string;
  blurb: string;
  genre: string;
  subgenre: string | null;
  by: string | null;
  builtAt: string | null;
};

const SITES = catalog as CatalogSite[];

function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function truncate(s: string, max: number): string {
  if (s.length <= max) return s;
  return s.slice(0, max - 1).trimEnd() + "…";
}

// Attribute-targeted regex replace instead of exact-string matching (the
// approach sites/didscope uses) — this page's <title>/description/og:*/
// twitter:* tags don't all carry identical text to begin with, so matching
// each tag by its name/property attribute is more robust than requiring a
// shared literal string across all of them.
function setTag(html: string, re: RegExp, value: string): string {
  return html.replace(re, (_m, pre: string, post: string) => pre + value + post);
}
const TITLE_RE = /(<title>)[^<]*(<\/title>)/i;
const DESC_RE = /(<meta\s+name="description"\s+content=")[^"]*(")/i;
const OG_TITLE_RE = /(<meta\s+property="og:title"\s+content=")[^"]*(")/i;
const OG_DESC_RE = /(<meta\s+property="og:description"\s+content=")[^"]*(")/i;
const OG_URL_RE = /(<meta\s+property="og:url"\s+content=")[^"]*(")/i;
const TW_TITLE_RE = /(<meta\s+name="twitter:title"\s+content=")[^"]*(")/i;
const TW_DESC_RE = /(<meta\s+name="twitter:description"\s+content=")[^"]*(")/i;

function stampMeta(html: string, title: string, desc: string, url: string): string {
  const t = esc(truncate(title, 200));
  const d = esc(truncate(desc, 300));
  const u = esc(url);
  return setTag(
    setTag(
      setTag(setTag(setTag(setTag(html, TITLE_RE, t), DESC_RE, d), OG_TITLE_RE, t),
        OG_DESC_RE,
        d,
      ),
      OG_URL_RE,
      u,
    ),
    TW_TITLE_RE,
    t,
  ).replace(TW_DESC_RE, (_m, pre: string, post: string) => pre + d + post);
}

function monthYear(iso: string): string {
  return new Date(iso).toLocaleDateString("en-US", { month: "long", year: "numeric", timeZone: "UTC" });
}

// The static shell at "/", unmodified — used both as the base to stamp meta
// onto and as the not-found fallback. Deliberately NOT env.ASSETS.fetch(request):
// that resolves the *original* /site/<name>-shaped path against the static
// router, which 404s (there's no such file), so a mistyped or deleted site
// name would serve Cloudflare's bare 404 instead of the SPA — which has its
// own "no site named X" message once the client script runs. Fetching "/"
// keeps the browser's address bar on /site/<name> while still handing back
// a real 200 page.
async function shell(env: Env, request: Request): Promise<Response> {
  return env.ASSETS.fetch(new Request(new URL("/", request.url), { method: "GET" }));
}

async function stampedShell(env: Env, request: Request, title: string, desc: string, path: string): Promise<Response> {
  const base = await shell(env, request);
  const html = await base.text();
  const stamped = stampMeta(html, title, desc, `https://rateyourbuild.bisks.net${path}`);
  return new Response(stamped, {
    headers: { "content-type": "text/html; charset=utf-8", "cache-control": "public, max-age=300" },
  });
}

async function renderSitePage(env: Env, request: Request, name: string): Promise<Response> {
  const site = SITES.find((s) => s.name === name);
  if (!site) return shell(env, request);
  const bits = [`genre: ${site.genre}`];
  if (site.subgenre) bits.push(site.subgenre);
  if (site.builtAt) bits.push(`built ${monthYear(site.builtAt)}`);
  const desc = `${site.blurb} (${bits.join(" · ")}) Rate it 0-10 on rateyourbuild.`;
  return stampedShell(env, request, `rateyourbuild: ${site.title}`, desc, `/site/${encodeURIComponent(site.name)}`);
}

async function renderGenrePage(env: Env, request: Request, key: string): Promise<Response> {
  const meta = (GENRES as Record<string, { label: string; super: string; description: string }>)[key];
  if (!meta) {
    // A stray site.type outside the six documented genres (or a typo) — no
    // description to stamp either way, but the client still renders a bare
    // board for a real stray genre, so serve the SPA rather than a 404.
    return shell(env, request);
  }
  const count = SITES.filter((s) => s.genre === key).length;
  const desc = `${meta.description} ${count} site${count === 1 ? "" : "s"} in this genre so far.`;
  return stampedShell(env, request, `rateyourbuild: ${meta.label} genre`, desc, `/genre/${encodeURIComponent(key)}`);
}

async function renderSuperPage(env: Env, request: Request, key: string): Promise<Response> {
  const meta = (SUPERS as Record<string, { label: string; description: string }>)[key];
  if (!meta) return shell(env, request);
  return stampedShell(
    env,
    request,
    `rateyourbuild: ${meta.label}`,
    meta.description,
    `/super/${encodeURIComponent(key)}`,
  );
}

// Subgenre names aren't unique across genres (e.g. "leaderboard" appears
// under joke, tool, and toy) so this route — and its lookup — is always
// scoped to a (genre, subgenre) pair, unlike /genre and /super.
async function renderSubgenrePage(env: Env, request: Request, genreKey: string, subgenreKey: string): Promise<Response> {
  const count = SITES.filter((s) => s.genre === genreKey && s.subgenre === subgenreKey).length;
  if (!count) return shell(env, request);
  const genreMeta = (GENRES as Record<string, { label: string; super: string; description: string }>)[genreKey];
  const desc = `${count} site${count === 1 ? "" : "s"} tagged "${subgenreKey}" under the ${genreMeta?.label || genreKey} genre. Rate them 0-10 on rateyourbuild.`;
  return stampedShell(
    env,
    request,
    `rateyourbuild: ${subgenreKey} (${genreKey})`,
    desc,
    `/genre/${encodeURIComponent(genreKey)}/${encodeURIComponent(subgenreKey)}`,
  );
}

// /reviewer/<handle-or-did> — "a page where I can see mine, or all of
// another user's, reviews." The actual review list is client-rendered from
// the network-wide rating index (no server-side access to that data), but a
// shared reviewer link still deserves its own og:title/description instead
// of the generic front-page card, same reasoning as /site and /genre. Same
// resolve-then-stamp pattern as sites/didscope's /s/<handle>.
const APPVIEW = "https://public.api.bsky.app/xrpc/";
async function appviewJson(method: string, params: Record<string, string>): Promise<any> {
  const qs = new URLSearchParams(params).toString();
  const res = await fetch(`${APPVIEW}${method}?${qs}`, { cf: { cacheTtl: 60 } as unknown as Record<string, unknown> });
  if (!res.ok) throw new Error(`${method} ${res.status}`);
  return res.json();
}

async function renderReviewerPage(env: Env, request: Request, rawActor: string): Promise<Response> {
  const actor = rawActor.replace(/^@/, "").trim();
  if (!actor) return shell(env, request);
  try {
    const profile = await appviewJson("app.bsky.actor.getProfile", { actor });
    const handle = profile.handle || actor;
    const title = `rateyourbuild: @${handle}'s reviews`;
    const desc = `every rating and review @${handle} has written on rateyourbuild — RateYourMusic for @buildthis.bisks.net's back catalog.`;
    return stampedShell(env, request, title, desc, `/reviewer/${encodeURIComponent(rawActor)}`);
  } catch (_) {
    // Unresolvable handle/DID server-side (typo, deleted account, rate
    // limit) — still serve the live page; the client surfaces its own
    // "couldn't find that account" state once it tries the same lookup.
    return shell(env, request);
  }
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);

    const site = url.pathname.match(/^\/site\/([^/]+)\/?$/);
    if (site) return renderSitePage(env, request, decodeURIComponent(site[1]));

    const subgenre = url.pathname.match(/^\/genre\/([^/]+)\/([^/]+)\/?$/);
    if (subgenre) return renderSubgenrePage(env, request, decodeURIComponent(subgenre[1]), decodeURIComponent(subgenre[2]));

    const genre = url.pathname.match(/^\/genre\/([^/]+)\/?$/);
    if (genre) return renderGenrePage(env, request, decodeURIComponent(genre[1]));

    const sup = url.pathname.match(/^\/super\/([^/]+)\/?$/);
    if (sup) return renderSuperPage(env, request, decodeURIComponent(sup[1]));

    const reviewer = url.pathname.match(/^\/reviewer\/([^/]+)\/?$/);
    if (reviewer) return renderReviewerPage(env, request, decodeURIComponent(reviewer[1]));

    return env.ASSETS.fetch(request);
  },
};
