// Curated list of common, real English 3-letter words (lowercase, no proper
// nouns, no slurs/obscenities). Used as the dictionary for the sator-square
// solver. Deliberately conservative — better to miss an obscure word than to
// let a non-word slip into a "real 3 letter words" generator.
export const WORDS = [
  "ace","act","add","ado","aft","age","ago","aid","ail","aim","air","ale","all",
  "and","ant","any","ape","apt","arc","are","arm","art","ash","ask","ate","atm",
  "awe","axe","bad","bag","ban","bar","bat","bay","bed","bee","beg","bet","bib",
  "bid","big","bin","bit","boa","bob","bog","boo","bow","box","boy","bra","bud",
  "bug","bum","bun","bus","but","buy","bye","cab","cam","can","cap","car","cat",
  "caw","cob","cod","cog","con","coo","cop","cot","cow","coy","cry","cub","cue",
  "cup","cur","cut","dab","dad","dam","day","den","dew","dib","did","die","dig",
  "dim","din","dip","doe","dog","don","dot","dry","dub","due","dug","dye","ear",
  "eat","ebb","eel","egg","ego","elf","elk","elm","emu","end","era","erg","eve",
  "ewe","eye","fad","fan","far","fat","fax","fed","fee","few","fib","fig","fin",
  "fir","fit","fix","flu","fly","foe","fog","for","fox","fry","fun","fur","gab",
  "gag","gap","gas","gel","gem","get","gnu","god","gum","gun","gut","guy","gym",
  "had","ham","has","hat","hay","hen","her","hey","hid","him","hip","his","hit",
  "hob","hog","hop","hot","how","hub","hue","hug","hum","hut","ice","icy","imp",
  "ink","inn","ion","ire","irk","ivy","jab","jag","jam","jar","jaw","jay","jet",
  "jig","job","jog","jot","joy","jug","jut","keg","key","kid","kin","kit","lab",
  "lad","lag","lap","law","lax","lay","led","leg","let","lid","lie","lip","lit",
  "lob","log","lot","low","mad","man","map","mat","maw","may","men","met","mix",
  "mob","mod","mom","mop","mow","mud","mug","nab","nag","nap","net","new","nib",
  "nil","nip","nit","nod","nor","not","now","nun","nut","oak","oar","oat","odd",
  "ode","off","oft","oil","old","one","opt","orb","ore","our","out","owe","owl",
  "own","pad","pal","pan","par","pat","paw","pay","pea","peg","pen","pep","per",
  "pet","pew","pie","pig","pin","pit","ply","pod","pop","pot","pro","pub","pun",
  "pup","put","rag","ram","ran","rap","rat","raw","ray","red","rib","rid","rig",
  "rim","rip","rob","rod","rot","row","rub","rug","rum","run","rut","rye","sad",
  "sag","sap","sat","saw","say","sea","see","set","sew","she","shy","sin","sip",
  "sir","sit","six","ski","sky","sly","sob","sod","son","sow","soy","spa","spy",
  "sty","sub","sue","sum","sun","tab","tag","tan","tap","tar","tax","tea","ten",
  "the","thy","tie","tin","tip","toe","ton","too","top","tot","tow","toy","try",
  "tub","tug","two","use","van","vat","vet","vie","vow","wag","wan","war","was",
  "wax","way","web","wed","wee","wet","who","why","wig","win","wit","woe","wok",
  "won","wow","yak","yam","yap","yaw","yes","yet","yew","you","zap","zig","zip",
  "zoo",
];
