// museum Worker — served at the root of museum.bisks.net.
//
// A wing/room stamps its own og:title + og:description onto the static
// shell so a shared /wing/<genre> or /piece/<name> link unfurls as that
// specific room rather than one generic card for every URL (same pattern as
// sites/rateyourbuild's /site/<name>, sites/didscope's /s/<handle> — see
// notes/45-sharing-and-virality.md, tier 4). Everything else is static: the
// exhibit catalog is a build-time snapshot of every sites/*/site.json
// manifest (public/data/exhibits.json, regenerated by sync-exhibits.mjs).
import exhibits from "../public/data/exhibits.json";
import { GENRES } from "../public/lib/genres.js";

export interface Env {
  ASSETS: { fetch: (req: Request) => Promise<Response> };
}

type Exhibit = {
  name: string;
  url: string;
  title: string;
  blurb: string;
  wing: string;
  by: string | null;
  builtAt: string | null;
  mentionUri: string | null;
  reception: string | null;
};

const EXHIBITS = exhibits as Exhibit[];

function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function truncate(s: string, max: number): string {
  if (s.length <= max) return s;
  return s.slice(0, max - 1).trimEnd() + "…";
}

function setTag(html: string, re: RegExp, value: string): string {
  return html.replace(re, (_m, pre: string, post: string) => pre + value + post);
}
const TITLE_RE = /(<title>)[^<]*(<\/title>)/i;
const DESC_RE = /(<meta\s+name="description"\s+content=")[^"]*(")/i;
const OG_TITLE_RE = /(<meta\s+property="og:title"\s+content=")[^"]*(")/i;
const OG_DESC_RE = /(<meta\s+property="og:description"\s+content=")[^"]*(")/i;
const OG_URL_RE = /(<meta\s+property="og:url"\s+content=")[^"]*(")/i;
const TW_TITLE_RE = /(<meta\s+name="twitter:title"\s+content=")[^"]*(")/i;
const TW_DESC_RE = /(<meta\s+name="twitter:description"\s+content=")[^"]*(")/i;

function stampMeta(html: string, title: string, desc: string, url: string): string {
  const t = esc(truncate(title, 200));
  const d = esc(truncate(desc, 300));
  const u = esc(url);
  return setTag(
    setTag(
      setTag(setTag(setTag(setTag(html, TITLE_RE, t), DESC_RE, d), OG_TITLE_RE, t), OG_DESC_RE, d),
      OG_URL_RE,
      u,
    ),
    TW_TITLE_RE,
    t,
  ).replace(TW_DESC_RE, (_m, pre: string, post: string) => pre + d + post);
}

// Deliberately fetch "/" rather than env.ASSETS.fetch(request) for the
// dynamic paths below — /piece/<name> and /wing/<genre> have no matching
// static file, so fetching the original request 404s. Fetching "/" keeps
// the address bar on the deep link while still handing back the real shell
// (same trick as rateyourbuild's shell()).
async function shell(env: Env, request: Request): Promise<Response> {
  return env.ASSETS.fetch(new Request(new URL("/", request.url), { method: "GET" }));
}

async function stampedShell(env: Env, request: Request, title: string, desc: string, path: string): Promise<Response> {
  const base = await shell(env, request);
  const html = await base.text();
  const stamped = stampMeta(html, title, desc, `https://museum.bisks.net${path}`);
  return new Response(stamped, {
    headers: { "content-type": "text/html; charset=utf-8", "cache-control": "public, max-age=300" },
  });
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);
    const pieceMatch = url.pathname.match(/^\/piece\/([^/]+)\/?$/);
    if (pieceMatch) {
      const name = decodeURIComponent(pieceMatch[1]);
      const piece = EXHIBITS.find((e) => e.name === name);
      if (piece) {
        const desc = `${piece.blurb} Commissioned by ${piece.by || "person unknown"}. Full wall text, provenance, and critical reception at the Museum of the Internet.`;
        return stampedShell(env, request, `museum: ${piece.title}`, desc, `/piece/${encodeURIComponent(piece.name)}`);
      }
    }
    const wingMatch = url.pathname.match(/^\/wing\/([^/]+)\/?$/);
    if (wingMatch) {
      const key = decodeURIComponent(wingMatch[1]);
      const meta = (GENRES as Record<string, { label: string; description: string }>)[key];
      if (meta) {
        const count = EXHIBITS.filter((e) => e.wing === key).length;
        const desc = `${meta.description} ${count} piece${count === 1 ? "" : "s"} on display in this wing.`;
        return stampedShell(env, request, `museum: the ${meta.label} wing`, desc, `/wing/${encodeURIComponent(key)}`);
      }
    }
    return env.ASSETS.fetch(request);
  },
};
